id = "keithley_6221_2182a_delta_3706a"
name = "Keithley 6221 + 2182A Delta + 3706A"
version = "0.1.0b1"
api_version = "1.0"
core_requires = ">=0.11.4,<0.12"
frontend = "frontend:Keithley6221Delta3706AFrontend"
backend = "backend:Keithley6221Delta3706ABackend"
backend_type = "python"
dependencies = [
    "PyVISA>=1.16.2,<1.17",
]

[[columns]]
name = "Channel"

[[columns]]
name = "Resistance"
unit = "Ohm"

[[columns]]
name = "Current"
unit = "A"

[[columns]]
name = "StdDev"
unit = "Ohm"

[[columns]]
name = "SampleCount"

[[columns]]
name = "StatusCode"
