id = "keithley_2614b"
name = "Keithley 2614B Dual-Channel Resistance"
version = "0.1.0b1"
api_version = "1.1"
core_requires = ">=0.11.5,<0.12"
frontend = "frontend:Keithley2614BFrontend"
backend = "backend:Keithley2614BBackend"
backend_type = "python"
measurement_mode = "once_per_slot"
dependencies = [
    "PyVISA>=1.16.2,<1.17",
]

[[columns]]
name = "R1"
unit = "Ohm"

[[columns]]
name = "Voltage1"
unit = "V"

[[columns]]
name = "Current1"
unit = "A"

[[columns]]
name = "StatusCode1"

[[columns]]
name = "R2"
unit = "Ohm"

[[columns]]
name = "Voltage2"
unit = "V"

[[columns]]
name = "Current2"
unit = "A"

[[columns]]
name = "StatusCode2"
